# -*- coding: utf-8 -*-

"""
将所有天赋以及其分类联系起来.
"""

from .talent import Talent
from .talent_category import TalentCategory

association = [
    (TalentCategory.pve, Talent.warrior_pve_fury),
    (TalentCategory.pve, Talent.warrior_pve_arm),
    (TalentCategory.pve, Talent.warrior_pve_protect),
    (TalentCategory.pve, Talent.paladin_pve_retri),
    (TalentCategory.pve, Talent.paladin_pve_holy),
    (TalentCategory.pve, Talent.paladin_pve_protect),
    (TalentCategory.pve, Talent.dk_pve_blood_dps),
    (TalentCategory.pve, Talent.dk_pve_unholy_dps),
    (TalentCategory.pve, Talent.dk_pve_frost_dps),
    (TalentCategory.pve, Talent.dk_pve_blood_tank),
    (TalentCategory.pve, Talent.dk_pve_unholy_tank),
    (TalentCategory.pve, Talent.dk_pve_frost_tank),
    (TalentCategory.pve, Talent.hunter_pve_marksman),
    (TalentCategory.pve, Talent.hunter_pve_survival),
    (TalentCategory.pve, Talent.hunter_pve_beast),
    (TalentCategory.pve, Talent.shaman_pve_resto),
    (TalentCategory.pve, Talent.shaman_pve_elemental),
    (TalentCategory.pve, Talent.shaman_pve_enhancement),
    (TalentCategory.pve, Talent.rogue_pve_combat),
    (TalentCategory.pve, Talent.rogue_pve_assassin),
    (TalentCategory.pve, Talent.rogue_pve_subtlety),
    (TalentCategory.pve, Talent.druid_pve_balance),
    (TalentCategory.pve, Talent.druid_pve_resto),
    (TalentCategory.pve, Talent.druid_pve_cat),
    (TalentCategory.pve, Talent.druid_pve_bear),
    (TalentCategory.pve, Talent.mage_pve_fire),
    (TalentCategory.pve, Talent.mage_pve_arcane),
    (TalentCategory.pve, Talent.mage_pve_frost),
    (TalentCategory.pve, Talent.warlock_pve_demonology),
    (TalentCategory.pve, Talent.warlock_pve_affliction),
    (TalentCategory.pve, Talent.warlock_pve_destruction),
    (TalentCategory.pve, Talent.priest_pve_shadow),
    (TalentCategory.pve, Talent.priest_pve_disco),
    (TalentCategory.pve, Talent.priest_pve_holy),

    (TalentCategory.pvp, Talent.warrior_pvp_fury),
    (TalentCategory.pvp, Talent.warrior_pvp_arm),
    (TalentCategory.pvp, Talent.warrior_pvp_protect),
    (TalentCategory.pvp, Talent.paladin_pvp_retri),
    (TalentCategory.pvp, Talent.paladin_pvp_holy),
    (TalentCategory.pvp, Talent.paladin_pvp_protect),
    (TalentCategory.pvp, Talent.dk_pvp_blood),
    (TalentCategory.pvp, Talent.dk_pvp_unholy),
    (TalentCategory.pvp, Talent.dk_pvp_frost),
    (TalentCategory.pvp, Talent.hunter_pvp_marksman),
    (TalentCategory.pvp, Talent.hunter_pvp_survival),
    (TalentCategory.pvp, Talent.hunter_pvp_beast),
    (TalentCategory.pvp, Talent.shaman_pvp_resto),
    (TalentCategory.pvp, Talent.shaman_pvp_elemental),
    (TalentCategory.pvp, Talent.shaman_pvp_enhancement),
    (TalentCategory.pvp, Talent.rogue_pvp_combat),
    (TalentCategory.pvp, Talent.rogue_pvp_assassin),
    (TalentCategory.pvp, Talent.rogue_pvp_subtlety),
    (TalentCategory.pvp, Talent.druid_pvp_balance),
    (TalentCategory.pvp, Talent.druid_pvp_resto),
    (TalentCategory.pvp, Talent.druid_pvp_cat),
    (TalentCategory.pvp, Talent.druid_pvp_bear),
    (TalentCategory.pvp, Talent.mage_pvp_fire),
    (TalentCategory.pvp, Talent.mage_pvp_arcane),
    (TalentCategory.pvp, Talent.mage_pvp_frost),
    (TalentCategory.pvp, Talent.warlock_pvp_demonology),
    (TalentCategory.pvp, Talent.warlock_pvp_affliction),
    (TalentCategory.pvp, Talent.warlock_pvp_destruction),
    (TalentCategory.pvp, Talent.priest_pvp_shadow),
    (TalentCategory.pvp, Talent.priest_pvp_disco),
    (TalentCategory.pvp, Talent.priest_pvp_holy),

    (TalentCategory.tank, Talent.warrior_pve_protect),
    (TalentCategory.tank, Talent.paladin_pve_protect),
    (TalentCategory.tank, Talent.druid_pve_bear),
    (TalentCategory.tank, Talent.dk_pve_blood_tank),
    (TalentCategory.tank, Talent.dk_pve_unholy_tank),
    (TalentCategory.tank, Talent.dk_pve_frost_tank),

    (TalentCategory.dps, Talent.warrior_pve_fury),
    (TalentCategory.dps, Talent.warrior_pve_arm),
    (TalentCategory.dps, Talent.paladin_pve_retri),
    (TalentCategory.dps, Talent.dk_pve_blood_dps),
    (TalentCategory.dps, Talent.dk_pve_unholy_dps),
    (TalentCategory.dps, Talent.dk_pve_frost_dps),
    (TalentCategory.dps, Talent.hunter_pve_marksman),
    (TalentCategory.dps, Talent.hunter_pve_survival),
    (TalentCategory.dps, Talent.hunter_pve_beast),
    (TalentCategory.dps, Talent.shaman_pve_elemental),
    (TalentCategory.dps, Talent.shaman_pve_enhancement),
    (TalentCategory.dps, Talent.rogue_pve_combat),
    (TalentCategory.dps, Talent.rogue_pve_assassin),
    (TalentCategory.dps, Talent.rogue_pve_subtlety),
    (TalentCategory.dps, Talent.druid_pve_balance),
    (TalentCategory.dps, Talent.druid_pve_cat),
    (TalentCategory.dps, Talent.mage_pve_fire),
    (TalentCategory.dps, Talent.mage_pve_arcane),
    (TalentCategory.dps, Talent.mage_pve_frost),
    (TalentCategory.dps, Talent.warlock_pve_demonology),
    (TalentCategory.dps, Talent.warlock_pve_affliction),
    (TalentCategory.dps, Talent.warlock_pve_destruction),
    (TalentCategory.dps, Talent.priest_pve_shadow),

    (TalentCategory.healer, Talent.paladin_pve_holy),
    (TalentCategory.healer, Talent.shaman_pve_resto),
    (TalentCategory.healer, Talent.druid_pve_resto),
    (TalentCategory.healer, Talent.priest_pve_disco),
    (TalentCategory.healer, Talent.priest_pve_holy),

    (TalentCategory.melee, Talent.warrior_pve_fury),
    (TalentCategory.melee, Talent.warrior_pve_arm),
    (TalentCategory.melee, Talent.warrior_pve_protect),
    (TalentCategory.melee, Talent.paladin_pve_retri),
    (TalentCategory.melee, Talent.paladin_pve_protect),
    (TalentCategory.melee, Talent.dk_pve_blood_dps),
    (TalentCategory.melee, Talent.dk_pve_unholy_dps),
    (TalentCategory.melee, Talent.dk_pve_frost_dps),
    (TalentCategory.melee, Talent.dk_pve_blood_tank),
    (TalentCategory.melee, Talent.dk_pve_unholy_tank),
    (TalentCategory.melee, Talent.dk_pve_frost_tank),
    (TalentCategory.melee, Talent.shaman_pve_enhancement),
    (TalentCategory.melee, Talent.rogue_pve_combat),
    (TalentCategory.melee, Talent.rogue_pve_assassin),
    (TalentCategory.melee, Talent.rogue_pve_subtlety),
    (TalentCategory.melee, Talent.druid_pve_cat),
    (TalentCategory.melee, Talent.druid_pve_bear),
    (TalentCategory.melee, Talent.warrior_pvp_fury),
    (TalentCategory.melee, Talent.warrior_pvp_arm),
    (TalentCategory.melee, Talent.warrior_pvp_protect),
    (TalentCategory.melee, Talent.paladin_pvp_retri),
    (TalentCategory.melee, Talent.paladin_pvp_protect),
    (TalentCategory.melee, Talent.dk_pvp_blood),
    (TalentCategory.melee, Talent.dk_pvp_unholy),
    (TalentCategory.melee, Talent.dk_pvp_frost),
    (TalentCategory.melee, Talent.shaman_pvp_enhancement),
    (TalentCategory.melee, Talent.rogue_pvp_combat),
    (TalentCategory.melee, Talent.rogue_pvp_assassin),
    (TalentCategory.melee, Talent.rogue_pvp_subtlety),
    (TalentCategory.melee, Talent.druid_pvp_cat),
    (TalentCategory.melee, Talent.druid_pvp_bear),

    (TalentCategory.ranger, Talent.paladin_pve_holy),
    (TalentCategory.ranger, Talent.hunter_pve_marksman),
    (TalentCategory.ranger, Talent.hunter_pve_survival),
    (TalentCategory.ranger, Talent.hunter_pve_beast),
    (TalentCategory.ranger, Talent.shaman_pve_resto),
    (TalentCategory.ranger, Talent.shaman_pve_elemental),
    (TalentCategory.ranger, Talent.shaman_pve_enhancement),
    (TalentCategory.ranger, Talent.druid_pve_balance),
    (TalentCategory.ranger, Talent.druid_pve_resto),
    (TalentCategory.ranger, Talent.mage_pve_fire),
    (TalentCategory.ranger, Talent.mage_pve_arcane),
    (TalentCategory.ranger, Talent.mage_pve_frost),
    (TalentCategory.ranger, Talent.warlock_pve_demonology),
    (TalentCategory.ranger, Talent.warlock_pve_affliction),
    (TalentCategory.ranger, Talent.warlock_pve_destruction),
    (TalentCategory.ranger, Talent.priest_pve_shadow),
    (TalentCategory.ranger, Talent.priest_pve_disco),
    (TalentCategory.ranger, Talent.priest_pve_holy),
    (TalentCategory.ranger, Talent.paladin_pvp_holy),
    (TalentCategory.ranger, Talent.hunter_pvp_marksman),
    (TalentCategory.ranger, Talent.hunter_pvp_survival),
    (TalentCategory.ranger, Talent.hunter_pvp_beast),
    (TalentCategory.ranger, Talent.shaman_pvp_resto),
    (TalentCategory.ranger, Talent.shaman_pvp_elemental),
    (TalentCategory.ranger, Talent.druid_pvp_balance),
    (TalentCategory.ranger, Talent.druid_pvp_resto),
    (TalentCategory.ranger, Talent.mage_pvp_fire),
    (TalentCategory.ranger, Talent.mage_pvp_arcane),
    (TalentCategory.ranger, Talent.mage_pvp_frost),
    (TalentCategory.ranger, Talent.warlock_pvp_demonology),
    (TalentCategory.ranger, Talent.warlock_pvp_affliction),
    (TalentCategory.ranger, Talent.warlock_pvp_destruction),
    (TalentCategory.ranger, Talent.priest_pvp_shadow),
    (TalentCategory.ranger, Talent.priest_pvp_disco),
    (TalentCategory.ranger, Talent.priest_pvp_holy),

    (TalentCategory.physics, Talent.warrior_pve_fury),
    (TalentCategory.physics, Talent.warrior_pve_arm),
    (TalentCategory.physics, Talent.warrior_pve_protect),
    (TalentCategory.physics, Talent.paladin_pve_retri),
    (TalentCategory.physics, Talent.paladin_pve_protect),
    (TalentCategory.physics, Talent.dk_pve_blood_dps),
    (TalentCategory.physics, Talent.dk_pve_unholy_dps),
    (TalentCategory.physics, Talent.dk_pve_frost_dps),
    (TalentCategory.physics, Talent.dk_pve_blood_tank),
    (TalentCategory.physics, Talent.dk_pve_unholy_tank),
    (TalentCategory.physics, Talent.dk_pve_frost_tank),
    (TalentCategory.physics, Talent.hunter_pve_marksman),
    (TalentCategory.physics, Talent.hunter_pve_survival),
    (TalentCategory.physics, Talent.hunter_pve_beast),
    (TalentCategory.physics, Talent.shaman_pve_enhancement),
    (TalentCategory.physics, Talent.rogue_pve_combat),
    (TalentCategory.physics, Talent.rogue_pve_assassin),
    (TalentCategory.physics, Talent.rogue_pve_subtlety),
    (TalentCategory.physics, Talent.druid_pve_cat),
    (TalentCategory.physics, Talent.druid_pve_bear),
    (TalentCategory.physics, Talent.warrior_pvp_fury),
    (TalentCategory.physics, Talent.warrior_pvp_arm),
    (TalentCategory.physics, Talent.warrior_pvp_protect),
    (TalentCategory.physics, Talent.paladin_pvp_retri),
    (TalentCategory.physics, Talent.paladin_pvp_protect),
    (TalentCategory.physics, Talent.dk_pvp_blood),
    (TalentCategory.physics, Talent.dk_pvp_unholy),
    (TalentCategory.physics, Talent.dk_pvp_frost),
    (TalentCategory.physics, Talent.hunter_pvp_marksman),
    (TalentCategory.physics, Talent.hunter_pvp_survival),
    (TalentCategory.physics, Talent.hunter_pvp_beast),
    (TalentCategory.physics, Talent.shaman_pvp_enhancement),
    (TalentCategory.physics, Talent.rogue_pvp_combat),
    (TalentCategory.physics, Talent.rogue_pvp_assassin),
    (TalentCategory.physics, Talent.rogue_pvp_subtlety),
    (TalentCategory.physics, Talent.druid_pvp_cat),
    (TalentCategory.physics, Talent.druid_pvp_bear),

    (TalentCategory.caster, Talent.paladin_pve_holy),
    (TalentCategory.caster, Talent.shaman_pve_resto),
    (TalentCategory.caster, Talent.shaman_pve_elemental),
    (TalentCategory.caster, Talent.druid_pve_balance),
    (TalentCategory.caster, Talent.druid_pve_resto),
    (TalentCategory.caster, Talent.mage_pve_fire),
    (TalentCategory.caster, Talent.mage_pve_arcane),
    (TalentCategory.caster, Talent.mage_pve_frost),
    (TalentCategory.caster, Talent.warlock_pve_demonology),
    (TalentCategory.caster, Talent.warlock_pve_affliction),
    (TalentCategory.caster, Talent.warlock_pve_destruction),
    (TalentCategory.caster, Talent.priest_pve_shadow),
    (TalentCategory.caster, Talent.priest_pve_disco),
    (TalentCategory.caster, Talent.priest_pve_holy),
    (TalentCategory.caster, Talent.paladin_pvp_holy),
    (TalentCategory.caster, Talent.shaman_pvp_resto),
    (TalentCategory.caster, Talent.shaman_pvp_elemental),
    (TalentCategory.caster, Talent.druid_pvp_balance),
    (TalentCategory.caster, Talent.druid_pvp_resto),
    (TalentCategory.caster, Talent.mage_pvp_fire),
    (TalentCategory.caster, Talent.mage_pvp_arcane),
    (TalentCategory.caster, Talent.mage_pvp_frost),
    (TalentCategory.caster, Talent.warlock_pvp_demonology),
    (TalentCategory.caster, Talent.warlock_pvp_affliction),
    (TalentCategory.caster, Talent.warlock_pvp_destruction),
    (TalentCategory.caster, Talent.priest_pvp_shadow),
    (TalentCategory.caster, Talent.priest_pvp_disco),
    (TalentCategory.caster, Talent.priest_pvp_holy),


    (TalentCategory.warrior, warrior_pve_fury),
    (TalentCategory.warrior, warrior_pve_arm),
    (TalentCategory.warrior, warrior_pve_protect),
    (TalentCategory.warrior, warrior_pvp_fury),
    (TalentCategory.warrior, warrior_pvp_arm),
    (TalentCategory.warrior, warrior_pvp_protect),

    (TalentCategory.paladin, paladin_pve_retri),
    (TalentCategory.paladin, paladin_pve_holy),
    (TalentCategory.paladin, paladin_pve_protect),
    (TalentCategory.paladin, paladin_pvp_retri),
    (TalentCategory.paladin, paladin_pvp_holy),
    (TalentCategory.paladin, paladin_pvp_protect),

    (TalentCategory.dk, dk_pve_blood_dps),
    (TalentCategory.dk, dk_pve_unholy_dps),
    (TalentCategory.dk, dk_pve_frost_dps),
    (TalentCategory.dk, dk_pve_blood_tank),
    (TalentCategory.dk, dk_pve_unholy_tank),
    (TalentCategory.dk, dk_pve_frost_tank),
    (TalentCategory.dk, dk_pvp_blood),
    (TalentCategory.dk, dk_pvp_unholy),
    (TalentCategory.dk, dk_pvp_frost),

    (TalentCategory.hunter, hunter_pve_marksman),
    (TalentCategory.hunter, hunter_pve_survival),
    (TalentCategory.hunter, hunter_pve_beast),
    (TalentCategory.hunter, hunter_pvp_marksman),
    (TalentCategory.hunter, hunter_pvp_survival),
    (TalentCategory.hunter, hunter_pvp_beast),

    (TalentCategory.shaman, shaman_pve_resto),
    (TalentCategory.shaman, shaman_pve_elemental),
    (TalentCategory.shaman, shaman_pve_enhancement),
    (TalentCategory.shaman, shaman_pvp_resto),
    (TalentCategory.shaman, shaman_pvp_elemental),
    (TalentCategory.shaman, shaman_pvp_enhancement),

    (TalentCategory.rogue, rogue_pve_combat),
    (TalentCategory.rogue, rogue_pve_assassin),
    (TalentCategory.rogue, rogue_pve_subtlety),
    (TalentCategory.rogue, rogue_pvp_combat),
    (TalentCategory.rogue, rogue_pvp_assassin),
    (TalentCategory.rogue, rogue_pvp_subtlety),

    (TalentCategory.druid, druid_pve_balance),
    (TalentCategory.druid, druid_pve_resto),
    (TalentCategory.druid, druid_pve_cat),
    (TalentCategory.druid, druid_pve_bear),
    (TalentCategory.druid, druid_pvp_balance),
    (TalentCategory.druid, druid_pvp_resto),
    (TalentCategory.druid, druid_pvp_cat),
    (TalentCategory.druid, druid_pvp_bear),

    (TalentCategory.mage, mage_pve_fire),
    (TalentCategory.mage, mage_pve_arcane),
    (TalentCategory.mage, mage_pve_frost),
    (TalentCategory.mage, mage_pvp_fire),
    (TalentCategory.mage, mage_pvp_arcane),
    (TalentCategory.mage, mage_pvp_frost),

    (TalentCategory.warlock, warlock_pve_demonology),
    (TalentCategory.warlock, warlock_pve_affliction),
    (TalentCategory.warlock, warlock_pve_destruction),
    (TalentCategory.warlock, warlock_pvp_demonology),
    (TalentCategory.warlock, warlock_pvp_affliction),
    (TalentCategory.warlock, warlock_pvp_destruction),

    (TalentCategory.priest, priest_pve_shadow),
    (TalentCategory.priest, priest_pve_disco),
    (TalentCategory.priest, priest_pve_holy),
    (TalentCategory.priest, priest_pvp_shadow),
    (TalentCategory.priest, priest_pvp_disco),
    (TalentCategory.priest, priest_pvp_holy),
]

category_to_talent_mapper = {
    category: []
    for category in TalentCategory
}
for category, talent in association:
    category_to_talent_mapper[category].append(talent)

talent_to_category_mapper = {
    talent: []
    for talent in Talent
}
for category, talent in association:
    talent_to_category_mapper[talent].append(category)


def get_talent_by_category(category: TalentCategory):
    return category_to_talent_mapper[category]


def get_category_by_talent(talent):
    return talent_to_category_mapper[talent]
